# Generated by Django 2.2.7 on 2019-12-12 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='srock',
            new_name='stock',
        ),
    ]
