# Generated by Django 2.2.7 on 2019-12-13 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_auto_20191212_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renta',
            old_name='fecha_nacimiento',
            new_name='fecha',
        ),
    ]
